### ISSUE TITLE
function to customize the entire file name ?

### ISSUE THREAD

**Issue by xmoroccan** [siriusphp/upload#15]
Sometimes you don't want the original file name to be a part of the uploaded file name, is there a function to set the entire file name manualy, i already use `setSanitizerCallback()`, but it just concatenate the return value with the original name.

**sorry for my English**

**Comment by adrianmiu** [comment]
Depends on what you mean by "manually".

1. If you want file 'abc.jpg" to be uploaded as "prefix_timestamp.jpg" or "universally_unique_id.jpg" you can use the `sanitizerCallback`. Just construct the destination filename and return it.

2. If you want file 'abc.jpg' to be uploaded using a name provided by the user or an already predefined name (for example if you want to overwrite a file that already exists), you can 

a. alter the `$_FILES['file']['name']` (I haven't done this so I might be wrong) 
b. use `use` when building the sanitizer

```php
$destination = 'exact_file_name.jpg';
$sanitizer = function($name) use ($destination) {
   return $destination;
}
$uploadHandler->setSanitizerCallback($sanitizer);
```
