### ISSUE TITLE
how we can show Error Message

### ISSUE THREAD

**Issue by pcse7en** [siriusphp/upload#16]
how we can show error message .
i do it by 
`$messages = $Result->getMessages(); `
but not show any thing.
by var_dump show this:
`array(1) {
  [0]=>
  object(Sirius\Validation\ErrorMessage)#39 (2) {
    ["template":protected]=>
    string(89) "MY ERROR MESSAGE"
    ["variables":protected]=>
    array(3) {
      ["allowed"]=>
      array(3) {
        [0]=>
        string(3) "jpg"
        [1]=>
        string(3) "png"
        [2]=>
        string(4) "jpeg"
      }
      ["image_types"]=>
      string(14) "JPG, PNG, JPEG"
      ["value"]=>
      array(6) {
        ["name"]=>
        string(36) "d88e7a4e8d71be8dd949cff875004bfa.gif"
        ["type"]=>
        string(9) "image/gif"
        ["tmp_name"]=>
        string(45) "C:\Users\seven\AppData\Local\Temp\phpD08D.tmp"
        ["error"]=>
        int(0)
        ["size"]=>
        int(128421)
        ["original_name"]=>
        string(22) "ajax-loading-large.gif"
      }
    }
  }
}`

**Comment by adrianmiu** [comment]
The `Sirius\Validation\ErrorMessage` has a `__toString` method so you can do a foreach over the messages and echo them out.
