### ISSUE TITLE
Setting Validation Messages for imagewidth rule

### ISSUE THREAD

**Issue by yahyaerturan** [siriusphp/upload#19]
Hi,
I have to say first: this is a great library. `.lock` solution is a killing feature. Thank you.

I need to set validation messages in my own language for `imagewidth` and `imageheight` rule. There are two messages can be shown. One is for `min` and other is for `max`. How can we set it?

    $uploadHandler->addRule('imagewidth', 'min=100&max=150');

**Comment by adrianmiu** [comment]
@yahyaerturan this should work. at least with the latest version should work
