### ISSUE TITLE
How do i rename the file to be stored ?

### ISSUE THREAD

**Issue by amansatija** [siriusphp/upload#20]
i dont want to store the file with its actual name ...
is there a way i can tell the handler to rename the file to be stored ,..!!

**Comment by yahyaerturan** [comment]
You can use sanitizer callback as renamer. I am doing like this:

```php
function upload_renamer($raw_file_name)
{
    $fileName = pathinfo($raw_file_name, PATHINFO_FILENAME);
    $fileExt  = pathinfo($raw_file_name, PATHINFO_EXTENSION);
    return slug($fileName).'.'.slug($fileExt);
};

$uploadHandler->setSanitizerCallback('upload_renamer');
```

Surely you can call anything in the callback function.

**Comment by adrianmiu** [comment]
@amansatija yahyaerturan solution is the way to go
