### ISSUE TITLE
Getting the File Name After Processing

### ISSUE THREAD

**Issue by hstr0100** [siriusphp/upload#21]
Hi,

I'm wondering, how you're supposed to get the file name, after calling the $results->confirm() , if this variable is protected and don't have a getter? https://github.com/siriusphp/upload/blob/master/src/Result/File.php#L19

Your example at the README does not work anymore because $result->name is a iterator, not a item, and by looping through that iterator we will get instances of FIle /\

I don't wan't to use the callback to get the file name, because I woudn't be able to keep track of  invalid files and other stuff, and even if I try, everything would end up in a mess.

It's an easy fix, so, it would be a lot helpful if you could update the project allowing direct access to the post-processed  image data.

Regards

**Comment by adrianmiu** [comment]
$result->name should return the name of the file. Maybe your $result is a collection?
