### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by asadghazanfary** [siriusphp/upload#23]
hi @adrianmiu and thank you for response

my issue is when upload non image file this warning is appear.
![screenshot](https://cloud.githubusercontent.com/assets/5650939/26355823/52b94ab0-3fdf-11e7-8e89-98110073dbad.jpg)

`$uploadHandler->addRule('imageratio', ['ratio' => 1], '{label} should be a sqare image', 'pic');`

and another question is how can i show error message in your sample
`$messages = $result->getMessages();`

and show me with sample how can i set required rule for file input

sorry for many questions i asked.

thank you so much

**Comment by adrianmiu** [comment]
Before validating that the image has a specific ratio you would need to ensure it has some pixels, no?

```
$uploadHandler->addRule('uploadrequired');
$uploadHandler->addRule('imagewidth', 'min=1');
$uploadHandler->addRule('imageheight', 'min=1');
```

More on the documentation http://www.sirius.ro/php/sirius/upload/ and http://www.sirius.ro/php/sirius/validation/validation_rules.html
