### ISSUE TITLE
Call to undefined method Sirius\Upload\Result\File::save()

### ISSUE THREAD

**Issue by asadghazanfary** [siriusphp/upload#29]
hi

can i fix this error when use upload class?
`<?php
require_once '../core/config.php';
use Sirius\Upload\Handler as UploadHandler;

if (isset($_POST['btn_upload'])) {
    $uploadHandler = new UploadHandler(ROOT . 'upload-test');

// validation rules
    $uploadHandler->addRule('uploadrequired');
    $uploadHandler->addRule('extension', ['allowed' => ['jpg', 'jpeg', 'png']], '{label} should be a valid image (jpg, jpeg, png)', 'Profile picture');
    $uploadHandler->addRule('size', ['max' => '20M'], '{label} should have less than {max}', 'Profile picture');

    $result = $uploadHandler->process($_FILES['foo']); // ex: subdirectory/my_headshot.png

    if ($result->isValid()) {
        // do something with the image like attaching it to a model etc
        try {
            $profile->foo = $result->name;
            $profile->save();
            $result->confirm(); // this will remove the .lock file
        } catch (\Exception $e) {
            // something wrong happened, we don't need the uploaded files anymore
            $result->clear();
            throw $e;
        }
    } else {
        // image was not moved to the container, where are error messages
        $messages = $result->getMessages();

    }

}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
    <input type="file" name="foo" value="" />
    <input type="submit" name="btn_upload" value="Upload File"/>
</form>

</body>
</html>`

**Comment by adrianmiu** [comment]
@asadghazanfary You don't save the result of the upload. When you set up your uploader you specify where the file will be saved and the uploader will take care of it. Only thing you have to do is `confirm()` (which will remove the lock file http://www.sirius.ro/php/sirius/upload/file_locking.html ) or configure your uploader to `auto_confirm` http://www.sirius.ro/php/sirius/upload/upload_options.html
