### ISSUE TITLE
simply handle all files

### ISSUE THREAD

**Issue by hlb-schmidt** [siriusphp/upload#30]
(how) can we simply handle all uploaded files?

im trying to migrate away from https://framework.zend.com/manual/1.11/en/zend.file.transfer.introduction.html and there we simply need to do:

```
$upload = new Zend_File_Transfer();
$files = $upload->getFileInfo();
foreach ($files as $file) ....
```

and i'm on a guest to find a same simple usage:

- i dont have to know identifiers in $_FILES
- i can simply loop over all uploaded files

ps. please note that the files are in `$_FILES["whatever_<number>"]`, and cause the `<number>` is crucial for frontend, i cannot use `whatever[]`. and anyway, if i want to handle all files, there is no need for me to know their identifiers in `$_FILES`.

**Comment by adrianmiu** [comment]
@hlb-schmidt Unfortunately you have to specify a key to be used for extracting the file from `$_FILES`. From the docs http://www.sirius.ro/php/sirius/upload/upload_aggregator.html probably the best solution would be

```php
use Sirius\Upload\HandlerAggregate as UploadHandlerAggregate;

$uploadHandlerAggregate = new UploadHandlerAggregate();
foreach (array_keys($_FILES) as $key) {
    // here you can also check if $key is valid
    $uploadHandlerAggregate->addHandler($key, $previouslyCreatedUploadHandler);
}
```
