### ISSUE TITLE
Exception is thrown if an associative array is passed in.

### ISSUE THREAD

**Issue by bobdenotter** [siriusphp/upload#32]
See screenshot: 

![Screenshot 2020-03-14 at 11 18 36](https://user-images.githubusercontent.com/1833361/76680052-bcf04300-65e5-11ea-8833-1422e5bc592e.png)

PR is coming up!

**Comment by adrianmiu** [comment]
@bobdenotter I've accepted your PR and I've published a new release

**Comment by bobdenotter** [comment]
Thanks! Works like a charm! ✨
