### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by realrecordzLab** [siriusphp/upload#35]
How I can manage multiple files upload? I need to do some operations when each single file is uploaded, I've read the documentation and I've added the upload aggregator but it's not clear if I need to iterate over the PSR-7 UploadedFileInterface `$request->getUploadedFiles()` object provided by Slim 4 or if the aggregator will take care of this and I can simply do my operations on the uploaded files one time after the `$result->isValid()` return a true value. 

```
$app->post('/upload', function(Request $request, Response $response){

    $uploadHandler = new UploadHandler(TMPDIR);
    $uploadHandler->addRule('extension', ['allowed' => ['jpg', 'jpeg', 'png']]);
    $uploadHandlerAggregate = new UploadHandlerAggregate();
    $uploadHandlerAggregate->addHandler('images', $uploadHandler);
    
    $result = $uploadHandlerAggregate->process( $request->getUploadedFiles() );
    
    if( $result->isValid() ){
        $result->confirm();
        // File operations code here
    }
    
    return $response;
});
```

**Comment by adrianmiu** [comment]
` $uploadHandler->process($_FILES['images']);` will work if there are multiple files uploaded under the same name. Depending on the result of  `$request->getUploadedFiles('some_name')` you may need to preprocess it
