### ISSUE TITLE
upload files that are not images

### ISSUE THREAD

**Issue by gadget00** [siriusphp/upload#36]
Hi all,
I'm trying to implement sirius upload to uploa PDF files in a form, but eventhough I added the 'pdf' extension to the permitted files lists, it still gives me back an error saying the file "should be a valid image (jpg, jpeg, png)"

Doesn't the library allow other types of file or am I doing something wrong?

Thanks for the great work; hope for an answer soon

**Comment by dranzd** [comment]
> Hi all, I'm trying to implement sirius upload to uploa PDF files in a form, but eventhough I added the 'pdf' extension to the permitted files lists, it still gives me back an error saying the file "should be a valid image (jpg, jpeg, png)"
> 
> Doesn't the library allow other types of file or am I doing something wrong?
> 
> Thanks for the great work; hope for an answer soon

This library accepts other types of files and you might want to check your added rules specifically the upload extension one.  That one validates for which extensions are allowed.
