### ISSUE TITLE
Include PSR-*

### ISSUE THREAD

**Issue by gilbertoalbino** [siriusphp/upload#6]
Gosh, installing this package is a pain in the neck!
Please, include PSR-0 or PSR-4 support. 
Actually, I installed siriusphp/upload package, but it installed siriusphp/validation.
After handling the upload package installation, it can't find the validation previously installed.
Horrible! Have you tried installing it via composer?

**Comment by adrianmiu** [comment]
I have and it works. I will add the PSR-4 support though

**Comment by adrianmiu** [comment]
Fixed by 11d40336cdb7bb4338df1cb3b9d4ce6e13c66b6f
